# Generated by Django 5.1.1 on 2024-10-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('function', models.CharField(choices=[('Manager', 'Manager'), ('Engineer', 'Engineer'), ('Technician', 'Technician'), ('Administrator', 'Administrator'), ('Secretaire', 'Secretaire'), ('Informaticien', 'Informaticien'), ('Comptable', 'Comptable'), ('Directeur', 'Directeur')], max_length=50)),
                ('department', models.CharField(choices=[('Informatique', 'Informatique'), ('Administration', 'Administration'), ('Finance', 'Finance'), ('Technique', 'Technique'), ('Commercial', 'Commercial'), ('Communication', 'Communication'), ('Ressources-Humain', 'Ressources-Humain')], max_length=50)),
                ('province', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
